/*
 * EQUIPE : Joyce Mikaella das Mercês Aciole
            Pedro Henrique Ferreira Ramos
 */
package gui;

import java.awt.CardLayout;
import java.awt.Color;
import java.text.NumberFormat;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Pedido;
import modelo.Produto;
import modelo.Rendimento;

/**
 *
 * @author pedru
 */
public class TelaProdutos extends javax.swing.JFrame {
    public TelaProdutos() {
        initComponents();
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JPanel();
        menu1Label = new javax.swing.JLabel();
        menu2Label = new javax.swing.JLabel();
        menu3Label = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cartaoPanel = new javax.swing.JPanel();
        comprarPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaProd = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        labelProd = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        labelSubtotal = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        labelTotal = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        quantSpinner = new javax.swing.JSpinner();
        finalizarCompra = new javax.swing.JLabel();
        organizarPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        nomeProd = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        valorProd = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        quantProd = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        valorCompraField = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        adicionarProduto = new javax.swing.JLabel();
        limparCampos = new javax.swing.JLabel();
        removerProduto = new javax.swing.JLabel();
        editarProduto = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        historicoPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelaHistorico = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        investimentoTotalLabel = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        vendasTotalLabel = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lucroLabel = new javax.swing.JLabel();
        lucroPorcLabel = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(1, 198, 83));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(579, 556));
        setMinimumSize(new java.awt.Dimension(579, 556));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(559, 571));
        setResizable(false);

        header.setBackground(new java.awt.Color(1, 198, 83));

        menu1Label.setBackground(new java.awt.Color(0, 150, 62));
        menu1Label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menu1Label.setForeground(new java.awt.Color(255, 255, 255));
        menu1Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menu1Label.setText("Tela de Compras");
        menu1Label.setOpaque(true);
        menu1Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu1LabelMouseClicked(evt);
            }
        });

        menu2Label.setBackground(new java.awt.Color(1, 198, 83));
        menu2Label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menu2Label.setForeground(new java.awt.Color(255, 255, 255));
        menu2Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menu2Label.setText("Organizar Estoque");
        menu2Label.setOpaque(true);
        menu2Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu2LabelMouseClicked(evt);
            }
        });

        menu3Label.setBackground(new java.awt.Color(1, 198, 83));
        menu3Label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menu3Label.setForeground(new java.awt.Color(255, 255, 255));
        menu3Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menu3Label.setText("Historico e Rendimento");
        menu3Label.setOpaque(true);
        menu3Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu3LabelMouseClicked(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icons/icons8-close-window-19.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap())
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(menu1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menu2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menu3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(menu1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menu2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menu3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        cartaoPanel.setLayout(new java.awt.CardLayout());

        comprarPanel.setBackground(new java.awt.Color(1, 198, 83));
        comprarPanel.setMaximumSize(new java.awt.Dimension(579, 476));
        comprarPanel.setPreferredSize(new java.awt.Dimension(579, 476));

        tabelaProd.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tabelaProd.setForeground(new java.awt.Color(51, 51, 51));
        tabelaProd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Valor de Venda (preço)", "Valor de Compra", "Quantidade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaProd.setGridColor(new java.awt.Color(255, 255, 255));
        tabelaProd.setRowHeight(20);
        tabelaProd.setSelectionBackground(new java.awt.Color(1, 198, 83));
        tabelaProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaProdMouseClicked(evt);
            }
        });
        tabelaProd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabelaProdKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaProd);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Selecione um produto para compra-lo:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Produto selecionado:");

        labelProd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelProd.setForeground(new java.awt.Color(255, 255, 255));
        labelProd.setText("Nenhum produto selecionado");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Selecione a quantidade:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Valor unitario:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("R$");

        labelSubtotal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelSubtotal.setForeground(new java.awt.Color(255, 255, 255));
        labelSubtotal.setText("0.00");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Total:");

        labelTotal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelTotal.setForeground(new java.awt.Color(255, 255, 255));
        labelTotal.setText("0.00");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("R$");

        quantSpinner.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        quantSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        finalizarCompra.setBackground(new java.awt.Color(0, 150, 62));
        finalizarCompra.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        finalizarCompra.setForeground(new java.awt.Color(255, 255, 255));
        finalizarCompra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        finalizarCompra.setText("Finalizar Compra");
        finalizarCompra.setOpaque(true);
        finalizarCompra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                finalizarCompraMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout comprarPanelLayout = new javax.swing.GroupLayout(comprarPanel);
        comprarPanel.setLayout(comprarPanelLayout);
        comprarPanelLayout.setHorizontalGroup(
            comprarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(comprarPanelLayout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(jLabel10)
                .addGap(22, 22, 22)
                .addGroup(comprarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(comprarPanelLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelSubtotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(finalizarCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))
                    .addGroup(comprarPanelLayout.createSequentialGroup()
                        .addGroup(comprarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(quantSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(comprarPanelLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelTotal)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(comprarPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel4))
            .addGroup(comprarPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(comprarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addComponent(labelProd))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        comprarPanelLayout.setVerticalGroup(
            comprarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(comprarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(comprarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(labelProd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(comprarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(quantSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(comprarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(comprarPanelLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(comprarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(labelSubtotal)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(comprarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(labelTotal)
                            .addComponent(jLabel11))
                        .addContainerGap(16, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, comprarPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(finalizarCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))))
        );

        cartaoPanel.add(comprarPanel, "tela1");

        organizarPanel.setBackground(new java.awt.Color(1, 198, 83));
        organizarPanel.setForeground(new java.awt.Color(1, 198, 83));
        organizarPanel.setMaximumSize(new java.awt.Dimension(579, 476));
        organizarPanel.setPreferredSize(new java.awt.Dimension(579, 476));

        jPanel1.setBackground(new java.awt.Color(1, 198, 83));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Quantidade");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nome do produto");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Valor de venda ao cliente (preço)");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Valor de compra (investimento)");

        jLabel25.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Para remover um produto, antes selecione-o na tabela de Produtos da janela de Realizar Compra");

        jLabel26.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("Para editar um produto, antes selecione-o na tabela de Produtos da janela de Realizar Compra");

        adicionarProduto.setBackground(new java.awt.Color(0, 150, 62));
        adicionarProduto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        adicionarProduto.setForeground(new java.awt.Color(255, 255, 255));
        adicionarProduto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        adicionarProduto.setText("Adicionar Produto");
        adicionarProduto.setOpaque(true);
        adicionarProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adicionarProdutoMouseClicked(evt);
            }
        });

        limparCampos.setBackground(new java.awt.Color(0, 150, 62));
        limparCampos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        limparCampos.setForeground(new java.awt.Color(255, 255, 255));
        limparCampos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        limparCampos.setText("Limpar Campos");
        limparCampos.setOpaque(true);
        limparCampos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                limparCamposMouseClicked(evt);
            }
        });

        removerProduto.setBackground(new java.awt.Color(0, 150, 62));
        removerProduto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        removerProduto.setForeground(new java.awt.Color(255, 255, 255));
        removerProduto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        removerProduto.setText("Remover Produto");
        removerProduto.setOpaque(true);
        removerProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                removerProdutoMouseClicked(evt);
            }
        });

        editarProduto.setBackground(new java.awt.Color(0, 150, 62));
        editarProduto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        editarProduto.setForeground(new java.awt.Color(255, 255, 255));
        editarProduto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        editarProduto.setText("Editar Produto");
        editarProduto.setOpaque(true);
        editarProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editarProdutoMouseClicked(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("Ao editar um produto, você estará alterando apenas a sua quantidade disponível.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(nomeProd, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(valorProd, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valorCompraField, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(quantProd, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(adicionarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(removerProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(limparCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomeProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(valorProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(valorCompraField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quantProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(limparCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adicionarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removerProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel25)
                .addGap(18, 18, 18)
                .addComponent(jLabel26)
                .addGap(18, 18, 18)
                .addComponent(jLabel27)
                .addGap(46, 46, 46))
        );

        javax.swing.GroupLayout organizarPanelLayout = new javax.swing.GroupLayout(organizarPanel);
        organizarPanel.setLayout(organizarPanelLayout);
        organizarPanelLayout.setHorizontalGroup(
            organizarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 569, Short.MAX_VALUE)
            .addGroup(organizarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(organizarPanelLayout.createSequentialGroup()
                    .addGap(9, 9, 9)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        organizarPanelLayout.setVerticalGroup(
            organizarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 491, Short.MAX_VALUE)
            .addGroup(organizarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(organizarPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        cartaoPanel.add(organizarPanel, "tela2");

        historicoPanel.setBackground(new java.awt.Color(1, 198, 83));
        historicoPanel.setMaximumSize(new java.awt.Dimension(579, 476));

        tabelaHistorico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Valor Total (preço)", "Valor de Compra", "Quantidade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaHistorico.setRowHeight(20);
        jScrollPane3.setViewportView(tabelaHistorico);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Histórico de compras realizadas:");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Rendimento atual:");

        jPanel2.setBackground(new java.awt.Color(1, 198, 83));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Valor gasto em investimentos:   R$");

        investimentoTotalLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        investimentoTotalLabel.setForeground(new java.awt.Color(255, 255, 255));
        investimentoTotalLabel.setText("0.00");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Valor total das vendas realizadas:   R$");

        vendasTotalLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        vendasTotalLabel.setForeground(new java.awt.Color(255, 255, 255));
        vendasTotalLabel.setText("0.00");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Lucro:   R$");

        lucroLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lucroLabel.setForeground(new java.awt.Color(255, 255, 255));
        lucroLabel.setText("0.00");

        lucroPorcLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lucroPorcLabel.setForeground(new java.awt.Color(255, 255, 255));
        lucroPorcLabel.setText("0.00");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Lucro:   %");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel15)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lucroPorcLabel)
                    .addComponent(investimentoTotalLabel)
                    .addComponent(vendasTotalLabel)
                    .addComponent(lucroLabel))
                .addGap(22, 22, 22))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(investimentoTotalLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(vendasTotalLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lucroLabel)
                    .addComponent(jLabel17))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lucroPorcLabel)
                    .addComponent(jLabel18))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout historicoPanelLayout = new javax.swing.GroupLayout(historicoPanel);
        historicoPanel.setLayout(historicoPanelLayout);
        historicoPanelLayout.setHorizontalGroup(
            historicoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE)
            .addGroup(historicoPanelLayout.createSequentialGroup()
                .addGroup(historicoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(historicoPanelLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(historicoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)))
                    .addGroup(historicoPanelLayout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        historicoPanelLayout.setVerticalGroup(
            historicoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(historicoPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cartaoPanel.add(historicoPanel, "tela3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(cartaoPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cartaoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void limparCampos() {
        nomeProd.setText("");
        valorProd.setText("");
        quantProd.setText("");
        valorCompraField.setText("");
    }
    
    public double getSubtotal() throws ParseException {
        String subtotalString = tabelaProd.getValueAt(tabelaProd.getSelectedRow(), 2).toString();
        NumberFormat nf = NumberFormat.getInstance();
        double subtotal = nf.parse(subtotalString).doubleValue();
        System.out.println("subtotal da compra = " + subtotal);
        return subtotal / 10;
    }
    
    public double getTotal() throws ParseException {
        double subtotal = getSubtotal();
        int total = getQuantDesejada();
        return subtotal * total;
    }
    
    public String getTotalString() throws ParseException {
        NumberFormat nf = NumberFormat.getInstance();
        double total = getTotal();
        String totalString = String.valueOf(total);
        System.out.println("total da compra = " + totalString);
        return totalString;
    }
    
    public int getQuantDesejada() throws ParseException {
//        if (quantDesejada.equals("")) {
//            JOptionPane.showMessageDialog(null, "Por favor, digite a quantidade desejada", "Não é possível comprar 0 produtos", JOptionPane.ERROR_MESSAGE);
//            return 0;
//        } else {
//            NumberFormat nf = NumberFormat.getInstance();
//            int quantDesejadaValor = nf.parse(quantDesejada.getText()).intValue();
//            System.out.println("quantidade desejada = " + quantDesejadaValor);
//            return quantDesejadaValor;
//        }
        return (int) quantSpinner.getValue();
    }
    
    public Object getValor_compra() {
        Object valor_compra = tabelaProd.getValueAt(tabelaProd.getSelectedRow(), 3);
        return valor_compra;
    }
    
    public Object getCodigoProduto() {
        if(tabelaProd.getSelectedRow() != -1) {
            Object codigoProd;
            codigoProd = tabelaProd.getValueAt(tabelaProd.getSelectedRow(), 0);
            //codigo = Integer.parseInt((String) codigoProd);
            return codigoProd;
        } else {
            return 0;
        }
    }
    
    private void criaTabelaHistorico() throws ParseException {
        //cria o modelo da tabela
        DefaultTableModel modelo = (DefaultTableModel) tabelaHistorico.getModel();
        Object conteudoLinha[] = new Object[5];
        
        //adiciona os dados da compra na classe Pedido
        Pedido pedido = new Pedido(getCodigoProduto(),labelProd.getText(), getTotal(), (double) getValor_compra(), getQuantDesejada());

        //adiciona o pedido num ArrayList
        ArrayList<Pedido> listPedidos = new ArrayList<>();
        listPedidos.add(pedido);
        
        for(int i=0; i < listPedidos.size(); i++) {
            conteudoLinha[0] = listPedidos.get(i).getCodigo();
            conteudoLinha[1] = listPedidos.get(i).getNome();
            conteudoLinha[2] = listPedidos.get(i).getValor();
            conteudoLinha[3] = listPedidos.get(i).getValor_compra();
            conteudoLinha[4] = listPedidos.get(i).getQuantidade();
            modelo.addRow(conteudoLinha);
        }
        
        atualizarAposCompra();
    }
    
    public void atualizarAposCompra() throws ParseException {
        int novaQuant = (int) tabelaProd.getValueAt(tabelaProd.getSelectedRow(), 4) - getQuantDesejada();
        if(tabelaProd.getSelectedRow() != -1) {
            tabelaProd.setValueAt(novaQuant, tabelaProd.getSelectedRow(), 4);
            if(novaQuant <= 0) {
                //DefaultTableModel modelo = (DefaultTableModel) tabelaProd.getModel();
                //modelo.removeRow(tabelaProd.getSelectedRow());
            }
        }
        
        vendasTotalLabel.setText(CalculaVendasTotal());
        lucroLabel.setText(CalculaLucroReais());
        lucroPorcLabel.setText(CalculaLucroPorc());
    }
    
    private String CalculaInvestimentoTotal() throws ParseException {
        Double investimento = 0.0;
        for ( int i = 0; i < tabelaProd.getRowCount(); i++){
            investimento += ((Double.parseDouble(tabelaProd.getValueAt(i, 3).toString()) * 
                    Integer.parseInt(tabelaProd.getValueAt(i, 4).toString()))
            );
//            System.out.println(Double.parseDouble(tabelaProd.getValueAt(i, 3).toString()));
//            System.out.println(Integer.parseInt(tabelaProd.getValueAt(tabelaProd.getSelectedRow(), 4).toString()));
//            System.out.println("quantidade desejada = " + getQuantDesejada());
        }
        System.out.println("valor investido = " + investimento);
        return investimento.toString();        
    }
    
    private String InvestimentoStr(Double investimento) {
        //adiciona Rendimento num ArrayList
        ArrayList<Double> listaRend = new ArrayList();
        listaRend.add(investimento);

        Double soma = null;
        //soma todos os valores de venda
        for(Double u : listaRend) {
            soma += u;
        }
        return soma.toString();
    }
    
//    private String RetornaInvestimentoTotal() {
//        InvestimentoStr();
//    }
    
    private String CalculaVendasTotal() {
        Double vendas = 0.0;
        for ( int i = 0; i < tabelaHistorico.getRowCount(); i++){
            vendas += Double.parseDouble(tabelaHistorico.getValueAt(i, 2).toString());
        }
        return vendas.toString();        
    }
    
    private String CalculaLucroReais() throws ParseException {
        Double investimento = Double.parseDouble(CalculaInvestimentoTotal());
        Double vendas = Double.parseDouble(CalculaVendasTotal());
        Double lucro = vendas - investimento;
        return lucro.toString();
    }
    
    private String CalculaLucroPorc() throws ParseException {
        Double lucro = Double.parseDouble(CalculaLucroReais());
        Double investimento = Double.parseDouble(CalculaInvestimentoTotal());
        Double porcentagem = lucro / investimento;
        return porcentagem.toString();
    }
    
    private void tabelaProdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabelaProdKeyReleased
        //
        if(tabelaProd.getSelectedRow() != -1) {
            quantProd.setText(tabelaProd.getValueAt(tabelaProd.getSelectedRow(), 3).toString());
            valorProd.setText(tabelaProd.getValueAt(tabelaProd.getSelectedRow(), 2).toString());

            //altera o conteúdo do labelProd para o nome do produto selecionado
            labelProd.setText(tabelaProd.getValueAt(tabelaProd.getSelectedRow(), 1).toString());

            //altera o conteúdo do labelSubtotal para o valor do produto unitário
            labelSubtotal.setText(tabelaProd.getValueAt(tabelaProd.getSelectedRow(), 2).toString());

            //altera o conteúdo do labelTotal para o valor unitário multiplicado pela quantidade

            try {
                labelTotal.setText(getTotalString());
            } catch (ParseException ex) {
                Logger.getLogger(TelaProdutos.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_tabelaProdKeyReleased

    private void tabelaProdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaProdMouseClicked
        // TODO add your handling code here:
        if(tabelaProd.getSelectedRow() != -1) {
            quantProd.setText(tabelaProd.getValueAt(tabelaProd.getSelectedRow(), 3).toString());
            valorProd.setText(tabelaProd.getValueAt(tabelaProd.getSelectedRow(), 2).toString());

            //altera o conteúdo do labelProd para o nome do produto selecionado
            labelProd.setText(tabelaProd.getValueAt(tabelaProd.getSelectedRow(), 1).toString());

            //altera o conteúdo do labelSubtotal para o valor do produto unitário
            labelSubtotal.setText(tabelaProd.getValueAt(tabelaProd.getSelectedRow(), 2).toString());

            //altera o conteúdo do labelTotal para o valor unitário multiplicado pela quantidade
            try {
                labelTotal.setText(getTotalString());
            } catch (ParseException ex) {
                Logger.getLogger(TelaProdutos.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_tabelaProdMouseClicked

    private void menu1LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu1LabelMouseClicked
        setLblColor(menu1Label);
        resetLblColor(menu2Label);
        resetLblColor(menu3Label);
        //alterna entre os jPanels
        organizarPanel.setVisible(false);
        historicoPanel.setVisible(false);
        comprarPanel.setVisible(true);
    }//GEN-LAST:event_menu1LabelMouseClicked

    private void menu2LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu2LabelMouseClicked
        setLblColor(menu2Label);
        resetLblColor(menu1Label);
        resetLblColor(menu3Label);
        //alterna entre os jPanels
        organizarPanel.setVisible(true);
        historicoPanel.setVisible(false);
        comprarPanel.setVisible(false);
    }//GEN-LAST:event_menu2LabelMouseClicked

    private void menu3LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu3LabelMouseClicked
        setLblColor(menu3Label);
        resetLblColor(menu1Label);
        resetLblColor(menu2Label);
        //alterna entre os jPanels
        organizarPanel.setVisible(false);
        historicoPanel.setVisible(true);
        comprarPanel.setVisible(false);
    }//GEN-LAST:event_menu3LabelMouseClicked

    // ------------switch between colors for Active/Inactive color
    public void setLblColor(JLabel lbl)
    {
        lbl.setBackground(new Color(0,150,62));
    }
    
      public void resetLblColor(JLabel lbl)
    {
        lbl.setBackground(new Color(1,198,83));
    }       
     //-----------End --------
      
    int xx;
    int xy;
    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        // TODO add your handling code here:
        xx = evt.getX();
        xy = evt.getY();
       
    }//GEN-LAST:event_headerMousePressed

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xx,y-xy);
    }//GEN-LAST:event_headerMouseDragged

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void finalizarCompraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_finalizarCompraMouseClicked
        if(tabelaProd.getSelectedRow() != -1) {
            try {
                if(getQuantDesejada() <= (int) tabelaProd.getValueAt(tabelaProd.getSelectedRow(), 4)) {
                    try {
                        criaTabelaHistorico();
                        JOptionPane.showMessageDialog(null, "Compra realizada com sucesso");
                    } catch (ParseException ex) {
                        Logger.getLogger(TelaProdutos.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Quantidade excedida para o produto escolhido", "Não foi possível realizer compra", JOptionPane.ERROR_MESSAGE);
                }
            } catch (ParseException ex) {
                Logger.getLogger(TelaProdutos.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Nenhum produto selecionado");
        }
    }//GEN-LAST:event_finalizarCompraMouseClicked

    private void adicionarProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adicionarProdutoMouseClicked
        //cria o modelo da tabela
        DefaultTableModel modelo = (DefaultTableModel) tabelaProd.getModel();
        Object conteudoLinha[] = new Object[5];
        
        int codProd = tabelaProd.getRowCount();
        codProd++;
        
         //adiciona na classe Produto
        Produto p = new Produto(codProd, 
                nomeProd.getText(), 
                Double.parseDouble(valorProd.getText()),
                Double.parseDouble(valorCompraField.getText()),
                Integer.parseInt(quantProd.getText())
        );
        
        //adiciona em um ArrayList
        ArrayList<Produto> listaProd = new ArrayList();
        listaProd.add(p);
        
        //adiciona do ArryList para a jTable tabelaProd
        for(int i=0; i < listaProd.size(); i++) {
            conteudoLinha[0] = listaProd.get(i).getCodigo();
            conteudoLinha[1] = listaProd.get(i).getNome();
            conteudoLinha[2] = listaProd.get(i).getValor_venda();
            conteudoLinha[3] = listaProd.get(i).getValor_compra();
            conteudoLinha[4] = listaProd.get(i).getQuantidade();
            modelo.addRow(conteudoLinha);
        }
        
        JOptionPane.showMessageDialog(null, "Produto adicionado ao estoque");
        
        //atualiza a label Investimento
        try {
            investimentoTotalLabel.setText(CalculaInvestimentoTotal());
        } catch (ParseException ex) {
            Logger.getLogger(TelaProdutos.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        //limpa os campos da tela Organizar Produtos
        limparCampos();
    }//GEN-LAST:event_adicionarProdutoMouseClicked

    private void limparCamposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_limparCamposMouseClicked
        // TODO add your handling code here:
        if(tabelaProd.getSelectedRow() != -1) {
//            tabelaProd.setValueAt(nomeProd.getText(), tabelaProd.getSelectedRow(), 1);
//            tabelaProd.setValueAt(valorProd.getText(), tabelaProd.getSelectedRow(), 2);
            tabelaProd.setValueAt(quantProd.getText(), tabelaProd.getSelectedRow(), 4);
            JOptionPane.showMessageDialog(null, "Produto atualizado com sucesso");
        } else {
            JOptionPane.showMessageDialog(null, "Nenhum produto selecionado. Selecione um produto para editá-lo!");
        }
    }//GEN-LAST:event_limparCamposMouseClicked

    private void removerProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removerProdutoMouseClicked
        //remove um produto da jTable
        if(tabelaProd.getSelectedRow() != -1) {
            DefaultTableModel modelo = (DefaultTableModel) tabelaProd.getModel();
            modelo.removeRow(tabelaProd.getSelectedRow());
            JOptionPane.showMessageDialog(null, "Produto removido com sucesso");
        } else {
            JOptionPane.showMessageDialog(null, "Nenhum produto selecionado. Selecione um produto da tabela para removê-lo");
        }
    }//GEN-LAST:event_removerProdutoMouseClicked

    private void editarProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editarProdutoMouseClicked
        // TODO add your handling code here:
        if(tabelaProd.getSelectedRow() != -1) {
//            tabelaProd.setValueAt(nomeProd.getText(), tabelaProd.getSelectedRow(), 1);
//            tabelaProd.setValueAt(valorProd.getText(), tabelaProd.getSelectedRow(), 2);
            tabelaProd.setValueAt(quantProd.getText(), tabelaProd.getSelectedRow(), 4);
            JOptionPane.showMessageDialog(null, "Produto atualizado com sucesso");
        } else {
            JOptionPane.showMessageDialog(null, "Nenhum produto selecionado. Selecione um produto para editá-lo!");
        }
    }//GEN-LAST:event_editarProdutoMouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaProdutos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adicionarProduto;
    private javax.swing.JPanel cartaoPanel;
    private javax.swing.JPanel comprarPanel;
    private javax.swing.JLabel editarProduto;
    private javax.swing.JLabel finalizarCompra;
    private javax.swing.JPanel header;
    private javax.swing.JPanel historicoPanel;
    private javax.swing.JLabel investimentoTotalLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel labelProd;
    private javax.swing.JLabel labelSubtotal;
    private javax.swing.JLabel labelTotal;
    private javax.swing.JLabel limparCampos;
    private javax.swing.JLabel lucroLabel;
    private javax.swing.JLabel lucroPorcLabel;
    private javax.swing.JLabel menu1Label;
    private javax.swing.JLabel menu2Label;
    private javax.swing.JLabel menu3Label;
    private javax.swing.JTextField nomeProd;
    private javax.swing.JPanel organizarPanel;
    private javax.swing.JTextField quantProd;
    private javax.swing.JSpinner quantSpinner;
    private javax.swing.JLabel removerProduto;
    public javax.swing.JTable tabelaHistorico;
    private javax.swing.JTable tabelaProd;
    private javax.swing.JTextField valorCompraField;
    private javax.swing.JTextField valorProd;
    private javax.swing.JLabel vendasTotalLabel;
    // End of variables declaration//GEN-END:variables
}
